# Generated by Django 5.2.13 on 2026-04-11 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fokontany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LienPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=20, unique=True, verbose_name='Numéro de CIN')),
                ('nom_prenom', models.CharField(max_length=150, verbose_name='Nom et Prénom')),
                ('lien', models.URLField(max_length=255, verbose_name='Lien du portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Cisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciscos', to='gestion_scolaire.dren')),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('fokontany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='gestion_scolaire.fokontany')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='gestion_scolaire.etablissement')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='gestion_scolaire.lienportfolio')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'unique_together': {('personne', 'etablissement', 'date_debut')},
            },
        ),
        migrations.AddField(
            model_name='lienportfolio',
            name='etablissements',
            field=models.ManyToManyField(related_name='liens_portfolio', through='gestion_scolaire.Presence', to='gestion_scolaire.etablissement'),
        ),
        migrations.CreateModel(
            name='Zap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cisco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaps', to='gestion_scolaire.cisco')),
            ],
        ),
        migrations.AddField(
            model_name='fokontany',
            name='zap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fokontanys', to='gestion_scolaire.zap'),
        ),
    ]
