# Generated by Django 5.2.13 on 2026-04-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_scolaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cisco',
            unique_together={('nom', 'dren')},
        ),
        migrations.AlterUniqueTogether(
            name='etablissement',
            unique_together={('nom', 'fokontany')},
        ),
        migrations.AlterUniqueTogether(
            name='fokontany',
            unique_together={('nom', 'zap')},
        ),
        migrations.AlterUniqueTogether(
            name='zap',
            unique_together={('nom', 'cisco')},
        ),
    ]
