# Generated by Django 5.2.13 on 2026-04-12 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_scolaire', '0002_alter_cisco_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur National'), ('DREN', 'Responsable DREN'), ('CISCO', 'Responsable CISCO'), ('ZAP', 'Responsable ZAP'), ('FOKONTANY', 'Responsable Fokontany'), ('ETAB', 'Directeur Établissement'), ('INVITE', 'Invité (Lecture seule)')], default='INVITE', max_length=20)),
                ('can_add', models.BooleanField(default=False, verbose_name='Peut Ajouter')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Peut Modifier')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Peut Supprimer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
