# Generated by Django 5.2.13 on 2026-04-12 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_scolaire', '0004_userprofile_dren_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cisco_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_scolaire.cisco'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='etablissement_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_scolaire.etablissement'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fokontany_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_scolaire.fokontany'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zap_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_scolaire.zap'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dren_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_scolaire.dren'),
        ),
    ]
